### ISSUE TITLE
Heroku discontinuing free plan

### ISSUE THREAD

**Issue by tech234a** [tech234a/irccloud#4]
Heroku will be discontinuing their free plan starting November 28, 2022.

This project will likely be updated to use GitHub Actions before then.

**Comment by tech234a** [comment]
This project has now been updated to use GitHub Actions.

**Comment by tech234a** [comment]
I will be monitoring the reliability of the GitHub Actions scheduling feature, it is currently configured to try to run on the 47th minute of every hour, but it tends to be delayed for me. As long as executions happen at least every ~2 hours users should stay connected.

**Comment by tech234a** [comment]
It seems that the scheduling feature for GitHub Actions may be too unreliable for this use case, I'll probably try Cloudflare Workers instead but that will likely require rewriting the connection logic.

**Comment by xfisbest** [comment]
> It seems that the scheduling feature for GitHub Actions may be too unreliable for this use case, I'll probably try Cloudflare Workers instead but that will likely require rewriting the connection logic.

possible to set this up for vps?

**Comment by tech234a** [comment]
> > It seems that the scheduling feature for GitHub Actions may be too unreliable for this use case, I'll probably try Cloudflare Workers instead but that will likely require rewriting the connection logic.
> 
> possible to set this up for vps?

Yeah should be possible if you have one. Just compile `main.go` and run it on an hourly schedule, providing the `IRCCLOUD_EMAIL` and `IRCCLOUD_PASSWORD` environment variables when you run the binary.

**Comment by xfisbest** [comment]
> > > It seems that the scheduling feature for GitHub Actions may be too unreliable for this use case, I'll probably try Cloudflare Workers instead but that will likely require rewriting the connection logic.
> > 
> > 
> > possible to set this up for vps?
> 
> Yeah should be possible if you have one. Just compile `main.go` and run it on an hourly schedule, providing the `IRCCLOUD_EMAIL` and `IRCCLOUD_PASSWORD` environment variables when you run the binary.

can you mention the commands to use?

**Comment by xfisbest** [comment]
> > > It seems that the scheduling feature for GitHub Actions may be too unreliable for this use case, I'll probably try Cloudflare Workers instead but that will likely require rewriting the connection logic.
> > 
> > 
> > possible to set this up for vps?
> 
> Yeah should be possible if you have one. Just compile `main.go` and run it on an hourly schedule, providing the `IRCCLOUD_EMAIL` and `IRCCLOUD_PASSWORD` environment variables when you run the binary.

i have no experience with go, a tutorial will be much appreciated.

**Comment by tech234a** [comment]
Here are some hints to point you in the right direction, more details are available if you search online: With `go` installed on your system, navigate to the directory with the source code, try running `go build`. Then run `crontab -e` and add a line similar to the following `7 * * * * IRCCLOUD_EMAIL={email}  IRCCLOUD_PASSWORD={password} {/path/to/compiled/binary}`, replacing the parts in `{}` with the appropriate values.

**Comment by xfisbest** [comment]
> Here are some hints to point you in the right direction, more details are available if you search online: With `go` installed on your system, navigate to the directory with the source code, try running `go build`. Then run `crontab -e` and add a line similar to the following `7 * * * * IRCCLOUD_EMAIL={email} IRCCLOUD_PASSWORD={password} {/path/to/compiled/binary}`, replacing the parts in `{}` with the appropriate values.

Didn't work, also if i simply use "IRCCLOUD_EMAIL={email} IRCCLOUD_PASSWORD={password} {/path/to/compiled/binary}" it says 
IRCCLOUD_EMAIL is required. but i have entered email correctly.

**Comment by tech234a** [comment]
> > Here are some hints to point you in the right direction, more details are available if you search online: With `go` installed on your system, navigate to the directory with the source code, try running `go build`. Then run `crontab -e` and add a line similar to the following `7 * * * * IRCCLOUD_EMAIL={email} IRCCLOUD_PASSWORD={password} {/path/to/compiled/binary}`, replacing the parts in `{}` with the appropriate values.
> 
> Didn't work, also if i simply use "IRCCLOUD_EMAIL={email} IRCCLOUD_PASSWORD={password} {/path/to/compiled/binary}" it says IRCCLOUD_EMAIL is required. Tried different syntax too.

Alternatively it might just be easier to hardcode the values at the bottom of `main.go` and recompile.

**Comment by xfisbest** [comment]
> Alternatively it might just be easier to hardcode the values at the bottom of `main.go` and recompile.

it's going perfect! till now. Cheers!

**Comment by tech234a** [comment]
> It seems that the scheduling feature for GitHub Actions may be too unreliable for this use case, I'll probably try Cloudflare Workers instead but that will likely require rewriting the connection logic.

I have completed the rewrite for Cloudflare Workers. Please open an issue if you find any problems.
